---
- name: Converge
  hosts: all

  vars:
    log2ram_state: install
    log2ram_reboot_after_install: false

  pre_tasks:
    - name: Update apt cache on Debian systems.
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Update pacman cache on Archlinux systems.
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_facts['os_family'] == "Archlinux"

  tasks:
    - name: Set correct variable to update log2ram.
      ansible.builtin.set_fact:
        log2ram_state: update

    - name: "Include log2ram"
      ansible.builtin.include_role:
        name: "ansible-role-log2ram"
