---
- name: Converge
  hosts: all

  vars:
    log2ram_state: install

  pre_tasks:
    - name: Update apt cache on Debian systems.
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update pacman cache on Archlinux systems.
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

  tasks:
    - name: Set correct variable to update log2ram.
      set_fact:
        log2ram_state: update

    - name: "Include log2ram"
      include_role:
        name: "ansible-role-log2ram"
