---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  PATH=${PATH}
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "chzerv/docker-${IMAGE:-debian}-ansible:${TAG:-latest}"
    command: ${DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
