---
- name: Customize log2ram.
  ansible.builtin.lineinfile:
    dest: /etc/log2ram.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
    mode: 0644
  with_items:
    - regexp: "^SIZE"
      line: "SIZE={{ log2ram_size }}"
    - regexp: "^USE_RSYNC"
      line: "USE_RSYNC={{ log2ram_use_rsync }}"
    - regexp: "^MAIL"
      line: "MAIL={{ log2ram_mail }}"
    - regexp: "^PATH_DISK"
      line: 'PATH_DISK="{{ log2ram_path_disk }}"'
    - regexp: "^ZL2R"
      line: "ZL2R={{ log2ram_use_zl2r }}"
    - regexp: "^COMP_ALG"
      line: "COMP_ALG={{ log2ram_compression_algorithm }}"
    - regexp: "^LOG_DISK_SIZE"
      line: "LOG_DISK_SIZE={{ log2ram_log_disk_size }}"
  changed_when: false
