---
- name: Install log2ram.
  include_tasks: "{{ item }}"
  vars:
    files:
      - "installation-{{ ansible_os_family }}.yml"
      - installation.yml
  loop: "{{ q('first_found', files, errors='ignore' ) }}"
  when: log2ram_state == "install"

- name: Check if log2ram is installed (Debian-based systems).
  package_facts:
    manager: auto
  when: ansible_os_family == "Debian"

- name: Check if log2ram is isntalled (Non-Debian systems).
  command: ls -l /usr/local/bin/log2ram
  register: log2ram_is_installed
  changed_when: false
  failed_when: false
  when: not ansible_os_family == "Debian"

- name: Set fact about installed packages in Debian.
  set_fact:
    log2ram_installed: "{{ ansible_facts.packages }}"
  when: ansible_os_family == "Debian"

- name: Set fact about installed packages in Non-Debian.
  set_fact:
    log2ram_installed: "{{ log2ram_is_installed.stdout }}"
  when: not ansible_os_family == "Debian"

- name: Uninstall log2ram.
  include_tasks: uninstall.yml
  when:
    - log2ram_state == "remove"
    - log2ram_installed | length > 0
