---
- name: Install log2ram.
  include_tasks: "{{ item }}"
  vars:
    files:
      - "installation-{{ ansible_os_family }}.yml"
      - installation.yml
  loop: "{{ q('first_found', files, errors='ignore' ) }}"
  when: log2ram_state == "install"

- name: Check if log2ram is installed (Debian-based systems).
  package_facts:
    manager: auto
  when: ansible_os_family == "Debian"

- name: Gather service facts.
  service_facts:

- name: Check if log2ram is installed (Non-Debian systems).
  command: ls -l /usr/local/bin/log2ram
  register: log2ram_is_installed
  changed_when: false
  failed_when: false
  when: not ansible_os_family == "Debian"

- name: Set fact about installed packages in Debian.
  set_fact:
    log2ram_installed: "{{ 'true' if 'log2ram' in ansible_facts.packages else 'false' }}"
  when:
    - ansible_os_family == "Debian"

- name: Set fact about installed packages in Non-Debian.
  set_fact:
    log2ram_installed: "{{ 'true' if log2ram_is_installed.stdout | length > 0 else 'false' }}"
  when:
    - not ansible_os_family == "Debian"

- name: Assert
  assert:
    that:
      - log2ram_installed | bool
    fail_msg: "log2ram installation failed!"
    success_msg: "log2ram installation was successful."
  when: log2ram_state == "install"

- name: Uninstall log2ram.
  include_tasks: uninstall.yml
  when:
    - log2ram_state == "remove"
    - log2ram_installed | bool

- name: Update log2ram.
  include_tasks: update.yml
  when:
    - log2ram_state == "update"
    - log2ram_installed | bool

- name: Configure log2ram.
  include_tasks: configuration.yml
  when: log2ram_installed | bool
