---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache on Debian systems.
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update pacman cache on Archlinux systems.
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

  tasks:
    - name: "Include log2ram"
      include_role:
        name: "ansible-role-log2ram"
