name: Import to Ansible Galaxy

on:
  push:
  schedule:
    - cron: 30 23 * * *

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
